# Generated by Django 6.1 on 2026-08-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='gif_url',
            field=models.URLField(blank=True, help_text='URL de un GIF demostrativo del ejercicio (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicios/'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='grupo_asignacion',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
